# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 800d9814710e04a880528e09bda3c5eee59f84620554179a905520c7f268718f4a6ea8d600fa04d3a4db6f4efdec28ef81add16318a64e61c3afaa5c2142f898

test:
  secret_key_base: 43bfaf09981a99c2b487043e5febe583287d0a4ac274c1e28ea16e29a8867362ef19ea452a55b464f3500e62ddc1edfe6e2c092507655eff73539316df156a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
